# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-23 05:22
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
    ]
