# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='content_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='content_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageblock',
            name='description_en',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='imageblock',
            name='description_es',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='imageblock',
            name='description_fr',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='imageblock',
            name='url_en',
            field=models.URLField(blank=True, help_text='Optional URL.', max_length=255, null=True, verbose_name='External URL'),
        ),
        migrations.AddField(
            model_name='imageblock',
            name='url_es',
            field=models.URLField(blank=True, help_text='Optional URL.', max_length=255, null=True, verbose_name='External URL'),
        ),
        migrations.AddField(
            model_name='imageblock',
            name='url_fr',
            field=models.URLField(blank=True, help_text='Optional URL.', max_length=255, null=True, verbose_name='External URL'),
        ),
        migrations.AddField(
            model_name='richblock',
            name='content_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='richblock',
            name='content_es',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='richblock',
            name='content_fr',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='richblock',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='richblock',
            name='title_es',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='richblock',
            name='title_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
    ]
